### ISSUE TITLE
[DOCS] Complete SecretJS Guide

### ISSUE THREAD

**Issue by norfmenn** [SecretFoundation/docs#113]
### Contact details

stoicnorth@protonmail.com OR on Discord --> Norfmenn#3396

### What type of request are you making?

New Content

### Describe your documentation request

SecretJS has been updated multiple times over the past few months. Our documentation has been updated to reflect the recent changes to SecretJS -- but only up until the 'transfer tokens - simple' example within the SecretJS-Templates. There are still several tutorials for how to use SecretJS missing from the documentation. 

You can find the templates to model the SecretJS tutorial from here: https://github.com/scrtlabs/SecretJS-Templates

For this issue to be complete tutorials for the following SecretJS-templates need to be added to the documentation: 

- [ ] npm run 4:advanced - Transfer tokens - advanced
- [ ] npm run 4:batch - Send multiple txs the same block
- [ ] npm run 4:batch_same_tx - Send multiple messages in the same transaction
- [ ] npm run 5 - Create, deploy and use a Secret Contract
- [ ] cd 6_wallets/keplr && npm i && npm run dev - Keplr wallet
- [ ] npm run 7 - SNIP-20 token. Creating and using fungible tokens
- [ ] cd 8_websocket && npm i && npm run dev - Consume Websocket contract events

The primary contributor working on the SecretJS-templates is @assafmo from Secret Labs.

**Comment by assafmo** [comment]
Hi, please note that 1 through 4 are already migrated on the `update-secretjs` branch https://github.com/scrtlabs/SecretJS-Templates/tree/update-secretjs

**Comment by srdtrk** [comment]
Yes using the update-secretjs branch is very important, and the already existing documentation on the latest version of secretjs might help you @StoicNorth 

https://github.com/scrtlabs/secret.js
