### ISSUE TITLE
Deprecate/redirect build.scrt.network 

### ISSUE THREAD

**Issue by levackt** [SecretFoundation/docs#123]
### What type of request are you making?

Other

### Describe your documentation request

Old docs at build.scrt.network can trip up new users, since the move to docs.scrt.network the page should perhaps redirect there, or even link to the new docs.

**Comment by assafmo** [comment]
I thought that I already did this, strange. 🤔

**Comment by StoicNorth** [comment]
It appears like the links are re-directing as expected. Going to close this issue. @levackt
