### ISSUE TITLE
[DOCS] Fix Run Full Node Documentation 

### ISSUE THREAD

**Issue by norfmenn** [SecretFoundation/docs#124]
### Contact details

stoicnorth@protonmail.com OR norfmenn#3396

### What type of request are you making?

Update Content

### Describe your documentation request

A few Secret Network community members have had trouble getting a node up and running by using the current state of documentation. This documentation needs to be updated to work as expected so developers can efficiently get their own nodes up and running.

**Comment by StoicNorth** [comment]
Need to add a tutorial on how to secure SSH with a yubikey.
