### ISSUE TITLE
[DOCS] Issue with directing users to SecretJS docs

### ISSUE THREAD

**Issue by srdtrk** [SecretFoundation/docs#126]
### Contact details

Srdtrk#3405

### What type of request are you making?

Broken Link

### Describe your documentation request

In the mainpage Readme.md, under the Docs header, there is a link [How to use SecretJS to develop Secret dApps](https://github.com/SecretFoundation/docs/blob/main/docs/cli/secretcli.md). This takes you to an unrelated link about secretcli

**Comment by StoicNorth** [comment]
Link is now fixed.
