### ISSUE TITLE
Documentation Revamp - [ Ecosystem overview ] 

### ISSUE THREAD

**Issue by ertemann** [SecretFoundation/docs#131]
Ecosystem overview chapter of Docs.scrt.network , link issues for separate headers.

- [ ]  Home (AWSM secret) - @ertemann
	- tools
		- block explorers
		- wallets
		- tx history
		- secure secret calls
- [ ]  Overview of entities/contributors - descriptions of the teams @ertemann, @pmuecke
	- Core 
		- scrt labs
		- foundation
		- committees
	- Core infrastructure (API/bridge validators)
		- citadel, secretnodes, relayers (stake lab, cryptocre notional lavender)
	- Application
		- secure secrets, hydro, jackal, domerium, etc
	- Tooling/community
		- trivium, secret sauce, gmail, pmuecke, secret saturn etc
- [ ]  Overview of applications (descriptions of the applications) - Education committee??
	- Secretswap
	- Siennaswap
	- Shade
	- btn
	- orbem wars
	- datavault
- [ ]  Funding - Ertemann/Education committe
	- Secret labs grants
	- Ecosystem fund (TBD)
	- Community pool
	- Shade grants
	- SNAC

**Comment by Defi-NicV** [comment]
not very experienced with you guys but i have a good handle on defi and am therefore requesting 'Overview of applications (descriptions of the applications)' 
short overview of what you expect and want and ill start tomorrow :()
