### ISSUE TITLE
[DOCS] Migration to gitbook

### ISSUE THREAD

**Issue by mohammedpatla** [SecretFoundation/docs#133]
### Contact details

mohammedp@securesecrets.org

### What type of request are you making?

New Content

### Describe your documentation request

So i had started this with the infra committee back before documentation got separated, 
Migrating the docs website to the gitbook setup, 
Currently, it's not automatic updated unfortunetly : [Gitbook Secret](https://scrt.gitbook.io/secret-network/branches)

I had given admin access to the Schultzie, but I know that at that point it was decided to continue on the docs.

Not sure if this is something the network would still want to maintain and do.

**Comment by dylanschultzie** [comment]
@mohammedpatla hey! I've added StoicNorth and Patrick to the admin panel so they also have access to it. 

The plan is still to migrate to gitbook.

**Comment by ertemann** [comment]
@dylanschultzie what do we have to do to migrate it? rather do it now or after finishing the revamp?

**Comment by StoicNorth** [comment]
Getting this migrated now. Will update if problems come up OR when it's ready!

**Comment by StoicNorth** [comment]
Migration complete.
