### ISSUE TITLE
Documentation Revamp - [ Development Overvew ]

### ISSUE THREAD

**Issue by thelmuxkriovar** [SecretFoundation/docs#134]
Development overview chapter of docs.scrt.network, link issues for separate headers.

Please create a new issue when taking on a task 

* overview - one page
  * [ ] for contract development
     * [ ] polar
     * [ ] toolkit
  * [ ] for frontend development
     * [ ] secretjs
     * [ ] keplr
     * [ ] griptape
  * [ ] for backend development
     * [ ] secret js
     * [ ] secret py
     * [ ] SecretCLI
* [ ] Testnet
* Secret contracts
  * [ ] Overview
     * [ ] Reference contracts
  * [ ] Core Components
     * [ ] Contract.rs
        * Init
        * Handles
        * queries
     * [ ] Msg.rs
        * Message definitions for init, handle, and queries
     * [ ] State.rs
        * Struct definitions and storage keys
     * [ ] Lib.rs
        * Holds names of all components .rs files
     * Schema.rs
  * [ ] Init
     * What should be in an init instead of handles.
     * Same purpose as a solidity constructor
  * [ ] Handles - **Assigned to Danny**
     * HandleMsg
     * HandleAnswer
  * [ ] Queries - **Assigned to Danny**
     * QueryMsg
     * QueryAnswer
  * [ ] Storage
     * Making/Handling storage keys, how they work. The fact that they all byte arrays, etc…
     * Saving to storage
     * Loading Storage
     * Removing storage
  * [ ] Viewing keys - **Assigned to Lumi**
     * Stored as an address and key pair, similar to username and password.
     * Why to use them
  * [ ] Certs and query permits - **Assigned to Lumi**
     * Why use certs as opposed to viewing keys in certain situations
  * [ ] How to use/create on chain entropy/randomness
  * [ ] Unique data handling
     * Uint128
        * When to use them instead of u128
        * Data hygiene, how Uint128s can sometimes be a security risk
     * Floats
        * DONT EVER USE THEM
  * [ ] Inter-Contract Interaction
     * CosmosMsg
     * Snip-20s
        * How to implement snip payments in your contract
        * Send vs Transfer
     * Regular inter contract handling
        * Init
        * Handles
        * Queries
  * [ ] HandleResponse
     * Messages
     * Logs
     * Data
  * [ ] Useful libraries
     * Secret-toolkit - this can be referenced in relevant sections where the toolkit is normally used. 
  * [ ] Contract Hashes
     * What they are, when they are needed
  * [ ] How to send native SCRT
  * [ ] Contract Calls From Front-End (Get Xiphs Input)
* Building a frontend
  * [ ] using clean secretjs
  * [ ] using griptape
* Building backend services
  * [ ] using the secretcli
  * [ ] using node.js
  * [ ] using python
* [ ] Vanilla cosmwasm migration
* [ ] Secret CLI - **Assigned to norfmenn**

**Comment by StoicNorth** [comment]
Can we add the dedicated section to using the Secret CLI to this? And assign it to me. I can take on everything CLI related because I was already working on updating this section previously.
