### ISSUE TITLE
[DOCS] Making a submodule for the documentation in the main scrtlabs/SecretNetwork repo for the docs?

### ISSUE THREAD

**Issue by mohammedpatla** [SecretFoundation/docs#139]
### What type of request are you making?

New Content

### Describe your documentation request

I have always wondered if we could link this repo as a submodule of the main repo. It would be nice to have both of them versions controlled by the parent, and auto-tag all documentation side-by-side during new releases or changes. But the documentation is maintained in this repo.

**Comment by dylanschultzie** [comment]
That's a great idea.

Documentation originally was in scrtlabs/secretnetwork, but that meant the only people who could make changes were those with write access. Yes, there are forks, but the review process was extraordinarily slow. Having this repo simply link over would be fantastic. Perhaps there's a way to symlink a docs dir? May not make sense, but who knows.
