### ISSUE TITLE
Full node documentation needs some update

### ISSUE THREAD

**Issue by sbellem** [SecretFoundation/docs#163]
Hi, just a few observations about the documentation.

## `secretd` version in installation instructions
In https://github.com/SecretFoundation/docs/blob/gitbook/node-runners/node-setup/install-secretd.md, could update the secretd version to the current latest, which is v1.4.0 at the time to writing this issue.
```
# download secretd v1.3.1
wget "https://github.com/scrtlabs/SecretNetwork/releases/download/v1.3.1/secretnetwork_1.3.1_mainnet_goleveldb_amd64.deb"

# verify download
echo "3b501e572ab6021df3371d5fae73952cd6fc5a85b726310cf32a000f4c093207 secretnetwork_1.3.1_mainnet_goleveldb_amd64.deb" | sha256sum --check
# secretnetwork_1.3.1_mainnet_goleveldb_amd64.deb: OK
```

Question: Where can one get the sha256 hash? See https://docs.scrt.network/secret-network-documentation/post-mortems-upgrades/upgrade-instructions/shockwave-delta#upgrading-manually

## bootstrap node URL
In https://github.com/SecretFoundation/docs/blob/gitbook/node-runners/node-setup/setup-full-node.md#configure-secretd:

```
secretd config chain-id secret-4
secretd config node https://lcd-secret.scrtlabs.com:443/rpc
secretd config output json
```

The URL https://lcd-secret.scrtlabs.com:443/rpc did not work in my setup attempts. Had to look at the API registry at https://github.com/scrtlabs/api-registry#secret-4-mainnet.

**Comment by ertemann** [comment]
Keeping install handles uptodate will become easier with current setup
