### ISSUE TITLE
Documentation lacks a direct link to Millionares Problem code

### ISSUE THREAD

**Issue by Miladinho** [SecretFoundation/docs#166]
In [this](https://github.com/SecretFoundation/docs/blob/gitbook/development/secret-by-example/millionaires-problem.md) guide there is a reference to the `msg.rs` code to view the `RicherResponse` struct, but I have no way of finding this file.

**Comment by writersblockchain** [comment]
[Updated!](https://docs.scrt.network/secret-network-documentation/development/secret-by-example/millionaires-problem)
