### ISSUE TITLE
Fix install links for secretcli from 1.3.1 to 1.6.1

### ISSUE THREAD

**Issue by leeweezee777** [SecretFoundation/docs#182]
Went through this document:

https://github.com/SecretFoundation/docs/blob/gitbook/development/getting-started/setting-up-your-environment.md

secretcli version 1.3.1 fails at the instantiate contract step in the following document:

https://github.com/SecretFoundation/docs/blob/gitbook/development/getting-started/compile-and-deploy.md

with error:

```
Failed to get IO key. Make sure the CLI and the node you are targeting are operating in the same SGX mode
2023/02/07 23:13:42 invalid character 'i' looking for beginning of value
Error: invalid character 'i' looking for beginning of value
```

Confirmed 1.6.0+ works as expected.

**Comment by writersblockchain** [comment]
[Updated! ](https://docs.scrt.network/secret-network-documentation/development/getting-started/setting-up-your-environment)
