### ISSUE TITLE
Missing sections in Ecosystem Overview beyond General Resources

### ISSUE THREAD

**Issue by egasimus** [SecretFoundation/docs#212]
We'd like to add Fadroma to the official docs, as it's still the first Secret Network-centric DevOps framework (although we went out of beta long after Polar and Griptape) and perhaps the only one actively maintained.

But where to add it? Products, Games, Explorers, Wallets, User Guides, Developer Guides, Developer Tools, Reference Contracts - all the links point to nowhere.

**Comment by mohammedpatla** [comment]
I would recommend a new section under developer tools. You should be able to create an .MD and document it. One you have something open a PR.

**Comment by ertemann** [comment]
@egasimus there is a page here https://docs.scrt.network/secret-network-documentation/development/tools-and-libraries/contract-development/fadroma that i created a long time ago.

I asked multiple times to different people of Fadroma to get them to help on writing an actual documentation piece on the tooling set and every time it doesnt move forward.

You know best what Fadroma does and we would gladly welcome any additions you would want to make. If you want to reference fadroma tools throughout guides and other pieces of docs if you think it would help then that too would be very welcome.

**Comment by ertemann** [comment]
I just recently restructured those sections and they will indeed remain in place.

Please feel free to contribute to them - @writersblockchain can help where needed as well to reference it further throughout the docs.
