### ISSUE TITLE
Developer documentation overhaul - Phase 1 

### ISSUE THREAD

**Issue by ertemann** [SecretFoundation/docs#31]
Issue which covers phase 1/6 of issue #30 

**Do quick repairs on the docs - make sure links work, nothing is immediately incorrect, etc.**

Some of this has been done already, but it’s clear that more attention needs done from a quick pass perspective. This is intended as a stopgap solution. Get in, so that while working on step 2, incoming developers are in a better state.

List of completed actions/necessary steps:

- [x] Check all links
- [x] etc
- [x] more

ETA before 23 january 2022

**Comment by moonstash** [comment]
Please tag me if you need anything merged🙏🏾
