### ISSUE TITLE
Review docs -> Protocol section

### ISSUE THREAD

**Issue by dylanschultzie** [SecretFoundation/docs#33]
Epic: #31 

- [x] Components
- [x] Encryption
- [x] Transactions
- [x] Intel SGX

**Comment by StoicNorth** [comment]
Transactions complete @dylanschultzie

**Comment by StoicNorth** [comment]
Intel SGX complete @dylanschultzie

**Comment by StoicNorth** [comment]
I've completed reviewing all protocol documentation. All that's left is a final review of the PR's and then resolving any further issues. @dylanschultzie
