### ISSUE TITLE
Phase 2 chartering plan

### ISSUE THREAD

**Issue by dylanschultzie** [SecretFoundation/docs#79]
This is the bulk of the short-term work. It will include going through every single step on all tutorials provided on https://docs.scrt.network/ 3 and Figment Learn | Secret 2, including fixing and improving upon them. Note that I don’t think figment currently accepts direct fixes, so this will be more involved.

I believe doing every tutorial is paramount to a job well done here, as reading over and reviewing the documentation isn’t the same as executing every command provided.

**Comment by dylanschultzie** [comment]
The ultimate goal of this section is to ensure accuracy, and ease of integration. Developer docs should simultaneously explain what's happening, and why, without being too complicated. Right now there's a "what to do", but not an explanation of why. What mindset should you have?

1. Start with [quickstart](https://docs.scrt.network/dev/quickstart.html). Do everything. **THIS NEEDS REDONE, EXPLAINS NOTHING**
2. Secret Tutorials, do everything.
3. Do Figment tutorials: https://learn.figment.io/protocols/secret

**Comment by dylanschultzie** [comment]
Goals:
1. Create a new doc for beginners. Create tutorials, show output, give examples. Link to Figment Training if necessary.
2. Clarify about OS requirements. Does M1 work (yes? possibly?), windows, etc.

**Comment by ertemann** [comment]
@dylanschultzie lets eliminate this in favor of the new overhaul. would be great to have this very detailed input highlighted in the structure document.

https://docs.google.com/document/d/16_GIEqJG5y_knQ2KNbZDj_NTFyaG4svth_aNIFk_it0/edit

**Comment by StoicNorth** [comment]
@ertemann Closing now so we can focused on the new doc issues.
